// ---------------------------------------------------------------------------
// Author:        David Gilinsky
// File:          src/daemon/main.cpp
// Purpose:       airwatcherd entry point: load config, connect to nwdb, register
//                the read-only NightWatcher extension tab, run the copier
//                scheduler, heartbeat, and deregister cleanly on shutdown.
// Created:       2026-07-22
// Last Modified: 2026-07-22
// Version:       0.1.0
// License:       GPL-3.0-or-later
// ---------------------------------------------------------------------------
#include <atomic>
#include <csignal>
#include <cstdio>
#include <ctime>
#include <exception>
#include <memory>
#include <string>

#include "airwatcher/version.hpp"  // generated by CMake
#include "config.hpp"
#include "copier.hpp"
#include "database.hpp"
#include "http_server.hpp"
#include "logging.hpp"

namespace {

std::atomic<bool> g_stop{false};
std::atomic<bool> g_reload{false};

void on_signal(int sig) {
    if (sig == SIGHUP) {
        g_reload.store(true);
    } else {
        g_stop.store(true);
    }
}

void usage(const char* prog) {
    std::printf(
        "airwatcherd " AIRWATCHER_VERSION " -- pull FITS frames off ASIAir devices.\n\n"
        "Usage: %s [--config PATH] [--version] [--help]\n\n"
        "  -c, --config PATH   configuration file (default /etc/airwatcher/airwatcher.conf)\n"
        "  -v, --version       print version and exit\n"
        "  -h, --help          this help\n",
        prog);
}

// Build the DB connection: password (and env overrides) from the environment,
// the connection target (host/port/user/name) from the config file.
airwatcher::DbConfig db_config(const airwatcher::Config& cfg) {
    airwatcher::DbConfig dbc = airwatcher::DbConfig::from_env();
    dbc.host = cfg.db_host;
    dbc.port = static_cast<uint16_t>(cfg.db_port);
    dbc.user = cfg.db_user;
    dbc.database = cfg.db_name;
    return dbc;
}

}  // namespace

int main(int argc, char** argv) {
    std::string config_path = "/etc/airwatcher/airwatcher.conf";
    for (int i = 1; i < argc; ++i) {
        const std::string a = argv[i];
        if (a == "--version" || a == "-v") { std::printf("airwatcherd %s\n", AIRWATCHER_VERSION); return 0; }
        if (a == "--help" || a == "-h") { usage(argv[0]); return 0; }
        if ((a == "--config" || a == "-c") && i + 1 < argc) config_path = argv[++i];
        else if (a.rfind("--config=", 0) == 0) config_path = a.substr(std::string("--config=").size());
    }

    struct sigaction sa{};
    sa.sa_handler = on_signal;
    sigemptyset(&sa.sa_mask);
    sigaction(SIGTERM, &sa, nullptr);
    sigaction(SIGINT, &sa, nullptr);
    sigaction(SIGHUP, &sa, nullptr);

    airwatcher::Config cfg;
    try {
        cfg = airwatcher::Config::load(config_path);
    } catch (const std::exception& e) {
        airwatcher::log_error(std::string("config: ") + e.what());
        return 1;
    }

    airwatcher::log_info(std::string("airwatcherd ") + AIRWATCHER_VERSION +
                         " starting (config " + config_path + ")");

    const airwatcher::DbConfig dbc = db_config(cfg);
    std::unique_ptr<airwatcher::Database> db;
    try {
        db = std::make_unique<airwatcher::Database>(dbc);
        db->ensure_schema();
    } catch (const std::exception& e) {
        airwatcher::log_error(std::string("database: ") + e.what());
        return 1;
    }

    if (cfg.ext_register) {
        try {
            db->register_extension(cfg.ext_name, cfg.ext_label, AIRWATCHER_VERSION,
                                   "airwatcher_status");
            airwatcher::log_info("registered NightWatcher extension '" + cfg.ext_name + "'");
        } catch (const std::exception& e) {
            airwatcher::log_warn(std::string("extension register: ") + e.what());
        }
    }

    airwatcher::Copier copier(cfg, dbc);
    copier.start();
    airwatcher::log_info("copier started (incoming " + cfg.incoming + ", poll " +
                         std::to_string(cfg.poll_interval_s) + "s)");

    airwatcher::HttpServer web(cfg, dbc);
    web.start();

    std::time_t last_hb = 0;
    while (!g_stop.load()) {
        if (g_reload.exchange(false)) {
            airwatcher::log_info("SIGHUP: active ASIAirs are re-read every poll");
        }
        const std::time_t now = std::time(nullptr);
        if (cfg.ext_register && now - last_hb >= cfg.heartbeat_seconds) {
            try {
                db->heartbeat(cfg.ext_name);
            } catch (const std::exception& e) {
                airwatcher::log_warn(std::string("heartbeat: ") + e.what());
            }
            last_hb = now;
        }
        const timespec ts{1, 0};
        nanosleep(&ts, nullptr);
    }

    airwatcher::log_info("airwatcherd stopping");
    web.stop();
    copier.stop();
    if (cfg.ext_register) {
        try {
            db->deregister(cfg.ext_name);  // drop the tab immediately
        } catch (const std::exception&) {
        }
    }
    return 0;
}
