// ---------------------------------------------------------------------------
// Author:        David Gilinsky
// File:          src/db/database.cpp
// Purpose:       Implementation of the MariaDB (libmariadb) database layer.
//                String inputs are escaped with mysql_real_escape_string;
//                numeric values are generated by this code, not user strings.
// Created:       2026-07-22
// Last Modified: 2026-10-07
// Version:       0.1.2
// License:       GPL-3.0-or-later
// ---------------------------------------------------------------------------
#include "database.hpp"

#include <mysql.h>

#include <algorithm>
#include <cstdlib>
#include <sstream>
#include <stdexcept>

namespace airwatcher {

struct Database::Impl {
    MYSQL* conn = nullptr;
};

namespace {

const char* env_any(std::initializer_list<const char*> names) {
    for (const char* n : names) {
        if (const char* v = std::getenv(n)) return v;
    }
    return nullptr;
}

}  // namespace

DbConfig DbConfig::from_env() {
    DbConfig c;
    if (const char* v = env_any({"AIRWATCHER_DB_HOST", "NWDB_HOST", "NW_DB_HOST"})) c.host = v;
    if (const char* v = env_any({"AIRWATCHER_DB_PORT", "NWDB_PORT", "NW_DB_PORT"}))
        c.port = static_cast<uint16_t>(std::atoi(v));
    if (const char* v = env_any({"AIRWATCHER_DB_USER", "NWDB_USER", "NW_DB_USER"})) c.user = v;
    if (const char* v = env_any({"AIRWATCHER_DB_PASSWORD", "NWDB_PASSWORD", "NW_DB_PASSWORD"}))
        c.password = v;
    if (const char* v = env_any({"AIRWATCHER_DB_NAME", "NWDB_NAME", "NW_DB_NAME"})) c.database = v;
    return c;
}

Database::Database(const DbConfig& cfg) : impl_(std::make_unique<Impl>()) {
    impl_->conn = mysql_init(nullptr);
    if (impl_->conn == nullptr) throw std::runtime_error("mysql_init failed");

    // Accept a convenience "host:port" form (single colon only, so IPv6 literals
    // are left alone). An explicit cfg.port still applies if no suffix is present.
    std::string host = cfg.host;
    unsigned int port = cfg.port;
    if (std::count(host.begin(), host.end(), ':') == 1) {
        const auto colon = host.find(':');
        const std::string p = host.substr(colon + 1);
        if (!p.empty() && p.find_first_not_of("0123456789") == std::string::npos) {
            port = static_cast<unsigned int>(std::atoi(p.c_str()));
            host = host.substr(0, colon);
        }
    }
    if (mysql_real_connect(impl_->conn, host.c_str(), cfg.user.c_str(), cfg.password.c_str(),
                           cfg.database.c_str(), port, nullptr, 0) == nullptr) {
        const std::string err = mysql_error(impl_->conn);
        mysql_close(impl_->conn);
        impl_->conn = nullptr;
        throw std::runtime_error("cannot connect to MariaDB (" + cfg.user + "@" + host + ":" +
                                 std::to_string(port) + "/" + cfg.database + "): " + err);
    }
    mysql_set_character_set(impl_->conn, "utf8mb4");
    mysql_autocommit(impl_->conn, 1);
}

Database::~Database() {
    if (impl_ && impl_->conn) mysql_close(impl_->conn);
}

std::string Database::esc(const std::string& s) {
    std::string out;
    out.resize(s.size() * 2 + 1);
    const unsigned long n =
        mysql_real_escape_string(impl_->conn, out.data(), s.c_str(), s.size());
    out.resize(n);
    return out;
}

void Database::exec(const std::string& sql) {
    if (mysql_query(impl_->conn, sql.c_str()) != 0) {
        throw std::runtime_error(std::string("query failed: ") + mysql_error(impl_->conn));
    }
}

std::vector<std::vector<std::string>> Database::query(const std::string& sql) {
    if (mysql_query(impl_->conn, sql.c_str()) != 0) {
        throw std::runtime_error(std::string("query failed: ") + mysql_error(impl_->conn));
    }
    MYSQL_RES* res = mysql_store_result(impl_->conn);
    std::vector<std::vector<std::string>> out;
    if (res == nullptr) return out;
    const unsigned nf = mysql_num_fields(res);
    MYSQL_ROW row;
    while ((row = mysql_fetch_row(res)) != nullptr) {
        const unsigned long* lens = mysql_fetch_lengths(res);
        std::vector<std::string> r;
        r.reserve(nf);
        for (unsigned i = 0; i < nf; ++i) {
            r.emplace_back(row[i] ? std::string(row[i], lens[i]) : std::string());
        }
        out.push_back(std::move(r));
    }
    mysql_free_result(res);
    return out;
}

// --------------------------------------------------------------------------
// Schema
// --------------------------------------------------------------------------
void Database::ensure_schema() {
    // The shared NightWatcher extension registry (same columns as the core's
    // sql/schema.sql). Created here too so AirWatcher works against a bare nwdb.
    exec(
        "CREATE TABLE IF NOT EXISTS extensions ("
        " name VARCHAR(32) NOT NULL,"
        " label VARCHAR(64) NULL,"
        " version VARCHAR(32) NULL,"
        " data_table VARCHAR(64) NULL,"
        " host VARCHAR(128) NULL,"
        " pid INT NULL,"
        " status VARCHAR(16) NOT NULL DEFAULT 'active',"
        " last_heartbeat DATETIME NULL,"
        " started_at DATETIME NULL,"
        " PRIMARY KEY (name)"
        ") ENGINE=InnoDB");

    // The shared NightWatcher operational event log (same columns as the core's
    // sql/schema.sql). Created IF NOT EXISTS so AirWatcher also works standalone.
    exec(
        "CREATE TABLE IF NOT EXISTS events ("
        " id BIGINT NOT NULL AUTO_INCREMENT,"
        " ts_utc DATETIME NOT NULL,"
        " device_id VARCHAR(32) NULL,"
        " source VARCHAR(32) NOT NULL,"
        " level ENUM('info','warning','error') NOT NULL DEFAULT 'info',"
        " event VARCHAR(64) NOT NULL,"
        " detail TEXT NULL,"
        " created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"
        " PRIMARY KEY (id),"
        " KEY idx_events_ts (ts_utc),"
        " KEY idx_events_device_ts (device_id, ts_utc)"
        ") ENGINE=InnoDB");

    // Per-ASIAir configuration.
    exec(
        "CREATE TABLE IF NOT EXISTS asiairs ("
        " id VARCHAR(64) NOT NULL,"
        " name VARCHAR(128) NULL,"
        " host VARCHAR(128) NOT NULL,"
        " smb_share VARCHAR(128) NULL,"
        " enabled TINYINT(1) NOT NULL DEFAULT 0,"
        " copy_mode VARCHAR(16) NOT NULL DEFAULT 'immediate',"
        " copy_n INT NOT NULL DEFAULT 0,"
        " copy_time VARCHAR(5) NULL,"
        " delete_after_copy TINYINT(1) NOT NULL DEFAULT 0,"
        " delete_mode VARCHAR(16) NOT NULL DEFAULT 'immediate',"
        " delete_n INT NOT NULL DEFAULT 0,"
        " delete_time VARCHAR(5) NULL,"
        " delete_via VARCHAR(8) NOT NULL DEFAULT 'none',"
        " ssh_user VARCHAR(64) NULL,"
        " timezone VARCHAR(64) NULL,"
        " notes TEXT NULL,"
        " created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),"
        " PRIMARY KEY (id)"
        ") ENGINE=InnoDB");

    // Per-file copy/delete state.
    // Every DATETIME AirWatcher owns holds UTC, written explicitly with
    // UTC_TIMESTAMP(); the column defaults are UTC too, so nothing can fall
    // back to the server's local clock (first_seen did until 0.1.2, and sat 7 h
    // behind copied_at on an MST server).
    exec(
        "CREATE TABLE IF NOT EXISTS airwatcher_files ("
        " id BIGINT NOT NULL AUTO_INCREMENT,"
        " asiair_id VARCHAR(64) NOT NULL,"
        " remote_path VARCHAR(500) NOT NULL,"
        " size BIGINT NOT NULL DEFAULT 0,"
        " first_seen DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),"
        " copied_at DATETIME NULL,"
        " deleted_at DATETIME NULL,"
        " PRIMARY KEY (id),"
        " UNIQUE KEY uq_air_path (asiair_id, remote_path),"
        " KEY idx_air_copied (asiair_id, copied_at)"
        ") ENGINE=InnoDB");

    // Status snapshot -- one row per ASIAir; this is the registered data_table.
    exec(
        "CREATE TABLE IF NOT EXISTS airwatcher_status ("
        " id BIGINT NOT NULL AUTO_INCREMENT,"
        " asiair VARCHAR(64) NOT NULL,"
        " ip VARCHAR(128) NULL,"
        " enabled TINYINT(1) NOT NULL DEFAULT 0,"
        " total_autorun BIGINT NOT NULL DEFAULT 0,"
        " remaining BIGINT NOT NULL DEFAULT 0,"
        " last_copy_utc DATETIME NULL,"
        " state VARCHAR(32) NULL,"
        " updated_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),"
        " PRIMARY KEY (id),"
        " UNIQUE KEY uq_asiair (asiair)"
        ") ENGINE=InnoDB");

    // Action log for AirWatcher's own UI.
    exec(
        "CREATE TABLE IF NOT EXISTS airwatcher_log ("
        " id BIGINT NOT NULL AUTO_INCREMENT,"
        " ts_utc DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),"
        " asiair VARCHAR(64) NULL,"
        " action VARCHAR(16) NOT NULL,"
        " file VARCHAR(500) NULL,"
        " status VARCHAR(16) NULL,"
        " detail TEXT NULL,"
        " PRIMARY KEY (id),"
        " KEY idx_awlog_ts (ts_utc)"
        ") ENGINE=InnoDB");

    // Existing installs created these columns with the server-local default;
    // CREATE TABLE IF NOT EXISTS leaves them alone, so set the UTC default
    // explicitly (metadata only, safe to repeat). Rows written before 0.1.2
    // still hold local time in first_seen/created_at: see README, Upgrading.
    for (const char* alter : {
             "ALTER TABLE airwatcher_files ALTER COLUMN first_seen SET DEFAULT (UTC_TIMESTAMP())",
             "ALTER TABLE airwatcher_log ALTER COLUMN ts_utc SET DEFAULT (UTC_TIMESTAMP())",
             "ALTER TABLE airwatcher_status ALTER COLUMN updated_at SET DEFAULT (UTC_TIMESTAMP())",
             "ALTER TABLE asiairs ALTER COLUMN created_at SET DEFAULT (UTC_TIMESTAMP())"}) {
        exec(alter);
    }
}

// --------------------------------------------------------------------------
// Extension registry + events
// --------------------------------------------------------------------------
void Database::register_extension(const std::string& name, const std::string& label,
                                  const std::string& version, const std::string& data_table) {
    exec("INSERT INTO extensions (name,label,version,data_table,host,pid,status,"
         "last_heartbeat,started_at) VALUES ('" + esc(name) + "','" + esc(label) + "','" +
         esc(version) + "','" + esc(data_table) + "',@@hostname,CONNECTION_ID(),'active',"
         "UTC_TIMESTAMP(),UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE label=VALUES(label),"
         "version=VALUES(version),data_table=VALUES(data_table),host=VALUES(host),"
         "pid=VALUES(pid),status='active',last_heartbeat=UTC_TIMESTAMP(),"
         "started_at=VALUES(started_at)");
}

void Database::heartbeat(const std::string& name) {
    exec("UPDATE extensions SET last_heartbeat=UTC_TIMESTAMP(),status='active' WHERE name='" +
         esc(name) + "'");
}

void Database::deregister(const std::string& name) {
    exec("UPDATE extensions SET status='stopped' WHERE name='" + esc(name) + "'");
}

void Database::log_event(const std::string& source, const std::string& level,
                         const std::string& event, const std::string& detail,
                         const std::string& device_id) {
    const std::string dev = device_id.empty() ? "NULL" : ("'" + esc(device_id) + "'");
    const std::string det = detail.empty() ? "NULL" : ("'" + esc(detail) + "'");
    exec("INSERT INTO events (ts_utc,device_id,source,level,event,detail) VALUES (UTC_TIMESTAMP()," +
         dev + ",'" + esc(source) + "','" + esc(level) + "','" + esc(event) + "'," + det + ")");
}

// --------------------------------------------------------------------------
// asiairs CRUD
// --------------------------------------------------------------------------
namespace {

const char* const kAsiairCols =
    "id,name,host,smb_share,enabled,copy_mode,copy_n,copy_time,delete_after_copy,"
    "delete_mode,delete_n,delete_time,delete_via,ssh_user,timezone,notes,created_at";

AsiairRow asiair_from_row(const std::vector<std::string>& r) {
    AsiairRow a;
    a.id = r[0]; a.name = r[1]; a.host = r[2]; a.smb_share = r[3];
    a.enabled = (r[4] == "1");
    a.copy_mode = r[5]; a.copy_n = std::atoi(r[6].c_str()); a.copy_time = r[7];
    a.delete_after_copy = (r[8] == "1");
    a.delete_mode = r[9]; a.delete_n = std::atoi(r[10].c_str()); a.delete_time = r[11];
    a.delete_via = r[12]; a.ssh_user = r[13]; a.timezone = r[14]; a.notes = r[15];
    a.created_at = r[16];
    return a;
}

}  // namespace

void Database::upsert_asiair(const std::string& id, const AsiairFields& f) {
    std::vector<std::string> cols{"id"};
    std::vector<std::string> vals{"'" + esc(id) + "'"};
    std::vector<std::string> ups;
    const auto addS = [&](const char* c, const std::optional<std::string>& v) {
        if (v) { cols.emplace_back(c); vals.push_back("'" + esc(*v) + "'");
                 ups.push_back(std::string(c) + "=VALUES(" + c + ")"); }
    };
    const auto addI = [&](const char* c, const std::optional<int>& v) {
        if (v) { cols.emplace_back(c); vals.push_back(std::to_string(*v));
                 ups.push_back(std::string(c) + "=VALUES(" + c + ")"); }
    };
    const auto addB = [&](const char* c, const std::optional<bool>& v) {
        if (v) { cols.emplace_back(c); vals.push_back(*v ? "1" : "0");
                 ups.push_back(std::string(c) + "=VALUES(" + c + ")"); }
    };
    addS("name", f.name); addS("host", f.host); addS("smb_share", f.smb_share);
    addB("enabled", f.enabled); addS("copy_mode", f.copy_mode); addI("copy_n", f.copy_n);
    addS("copy_time", f.copy_time); addB("delete_after_copy", f.delete_after_copy);
    addS("delete_mode", f.delete_mode); addI("delete_n", f.delete_n);
    addS("delete_time", f.delete_time); addS("delete_via", f.delete_via);
    addS("ssh_user", f.ssh_user); addS("timezone", f.timezone); addS("notes", f.notes);
    cols.emplace_back("created_at"); vals.emplace_back("UTC_TIMESTAMP()");   // insert only

    std::ostringstream q;
    q << "INSERT INTO asiairs (";
    for (size_t i = 0; i < cols.size(); ++i) { if (i) q << ","; q << cols[i]; }
    q << ") VALUES (";
    for (size_t i = 0; i < vals.size(); ++i) { if (i) q << ","; q << vals[i]; }
    q << ")";
    if (!ups.empty()) {
        q << " ON DUPLICATE KEY UPDATE ";
        for (size_t i = 0; i < ups.size(); ++i) { if (i) q << ","; q << ups[i]; }
    }
    exec(q.str());
}

bool Database::update_asiair(const std::string& id, const AsiairFields& f) {
    if (!find_asiair(id)) return false;
    std::vector<std::string> sets;
    const auto setS = [&](const char* c, const std::optional<std::string>& v) {
        if (v) sets.push_back(std::string(c) + "='" + esc(*v) + "'");
    };
    const auto setI = [&](const char* c, const std::optional<int>& v) {
        if (v) sets.push_back(std::string(c) + "=" + std::to_string(*v));
    };
    const auto setB = [&](const char* c, const std::optional<bool>& v) {
        if (v) sets.push_back(std::string(c) + "=" + (*v ? "1" : "0"));
    };
    setS("name", f.name); setS("host", f.host); setS("smb_share", f.smb_share);
    setB("enabled", f.enabled); setS("copy_mode", f.copy_mode); setI("copy_n", f.copy_n);
    setS("copy_time", f.copy_time); setB("delete_after_copy", f.delete_after_copy);
    setS("delete_mode", f.delete_mode); setI("delete_n", f.delete_n);
    setS("delete_time", f.delete_time); setS("delete_via", f.delete_via);
    setS("ssh_user", f.ssh_user); setS("timezone", f.timezone); setS("notes", f.notes);
    if (sets.empty()) return true;

    std::ostringstream q;
    q << "UPDATE asiairs SET ";
    for (size_t i = 0; i < sets.size(); ++i) { if (i) q << ","; q << sets[i]; }
    q << " WHERE id='" << esc(id) << "'";
    exec(q.str());
    return true;
}

bool Database::remove_asiair(const std::string& id) {
    if (!find_asiair(id)) return false;
    exec("DELETE FROM asiairs WHERE id='" + esc(id) + "'");
    exec("DELETE FROM airwatcher_files WHERE asiair_id='" + esc(id) + "'");
    return true;
}

std::vector<AsiairRow> Database::asiairs() {
    std::vector<AsiairRow> out;
    for (const auto& r : query(std::string("SELECT ") + kAsiairCols + " FROM asiairs ORDER BY id"))
        out.push_back(asiair_from_row(r));
    return out;
}

std::vector<AsiairRow> Database::active_asiairs() {
    std::vector<AsiairRow> out;
    for (const auto& r :
         query(std::string("SELECT ") + kAsiairCols + " FROM asiairs WHERE enabled=1 ORDER BY id"))
        out.push_back(asiair_from_row(r));
    return out;
}

std::optional<AsiairRow> Database::find_asiair(const std::string& id) {
    const auto rows =
        query(std::string("SELECT ") + kAsiairCols + " FROM asiairs WHERE id='" + esc(id) + "'");
    if (rows.empty()) return std::nullopt;
    return asiair_from_row(rows.front());
}

// --------------------------------------------------------------------------
// Per-file state
// --------------------------------------------------------------------------
void Database::mark_seen(const std::string& asiair_id, const std::string& path, long long size) {
    exec("INSERT INTO airwatcher_files (asiair_id,remote_path,size,first_seen) VALUES ('" +
         esc(asiair_id) + "','" + esc(path) + "'," + std::to_string(size) +
         ",UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE size=VALUES(size)");
}

std::string Database::first_seen_utc(const std::string& asiair_id, const std::string& path) {
    const auto rows = query("SELECT first_seen FROM airwatcher_files WHERE asiair_id='" +
                            esc(asiair_id) + "' AND remote_path='" + esc(path) + "'");
    return rows.empty() || rows[0].empty() ? std::string() : rows[0][0];
}

std::vector<std::string> Database::copied_paths(const std::string& asiair_id) {
    std::vector<std::string> out;
    for (const auto& r : query("SELECT remote_path FROM airwatcher_files WHERE asiair_id='" +
                               esc(asiair_id) + "' AND copied_at IS NOT NULL"))
        out.push_back(r[0]);
    return out;
}

void Database::mark_copied(const std::string& asiair_id, const std::string& path) {
    exec("UPDATE airwatcher_files SET copied_at=UTC_TIMESTAMP() WHERE asiair_id='" + esc(asiair_id) +
         "' AND remote_path='" + esc(path) + "'");
}

std::vector<std::string> Database::copied_not_deleted(const std::string& asiair_id) {
    std::vector<std::string> out;
    for (const auto& r : query("SELECT remote_path FROM airwatcher_files WHERE asiair_id='" +
                               esc(asiair_id) + "' AND copied_at IS NOT NULL AND deleted_at IS NULL"))
        out.push_back(r[0]);
    return out;
}

void Database::mark_deleted(const std::string& asiair_id, const std::string& path) {
    exec("UPDATE airwatcher_files SET deleted_at=UTC_TIMESTAMP() WHERE asiair_id='" +
         esc(asiair_id) + "' AND remote_path='" + esc(path) + "'");
}

// --------------------------------------------------------------------------
// Status snapshot + action log
// --------------------------------------------------------------------------
void Database::upsert_status(const std::string& asiair, const std::string& ip, bool enabled,
                             long long total_autorun, long long remaining,
                             const std::string& state, bool touch_last_copy) {
    const std::string lc = touch_last_copy ? "UTC_TIMESTAMP()" : "last_copy_utc";
    exec("INSERT INTO airwatcher_status (asiair,ip,enabled,total_autorun,remaining,state,"
         "last_copy_utc,updated_at) VALUES ('" + esc(asiair) + "','" + esc(ip) + "'," +
         (enabled ? "1" : "0") + "," + std::to_string(total_autorun) + "," +
         std::to_string(remaining) + ",'" + esc(state) + "'," +
         (touch_last_copy ? "UTC_TIMESTAMP()" : "NULL") + ",UTC_TIMESTAMP()) "
         "ON DUPLICATE KEY UPDATE ip=VALUES(ip),enabled=VALUES(enabled),"
         "total_autorun=VALUES(total_autorun),remaining=VALUES(remaining),state=VALUES(state),"
         "last_copy_utc=" + lc + ",updated_at=UTC_TIMESTAMP()");
}

void Database::clear_status(const std::string& asiair) {
    exec("DELETE FROM airwatcher_status WHERE asiair='" + esc(asiair) + "'");
}

void Database::log_action(const std::string& asiair, const std::string& action,
                          const std::string& file, const std::string& status,
                          const std::string& detail) {
    const std::string fl = file.empty() ? "NULL" : ("'" + esc(file) + "'");
    const std::string dt = detail.empty() ? "NULL" : ("'" + esc(detail) + "'");
    exec("INSERT INTO airwatcher_log (ts_utc,asiair,action,file,status,detail) VALUES "
         "(UTC_TIMESTAMP(),'" + esc(asiair) + "','" + esc(action) + "'," + fl + ",'" +
         esc(status) + "'," + dt + ")");
}

std::vector<std::vector<std::string>> Database::recent_log(int limit) {
    if (limit < 1) limit = 200;
    if (limit > 2000) limit = 2000;
    return query("SELECT ts_utc,asiair,action,file,status,detail FROM airwatcher_log "
                 "ORDER BY id DESC LIMIT " + std::to_string(limit));
}

std::vector<std::vector<std::string>> Database::status_rows() {
    return query("SELECT asiair,ip,enabled,total_autorun,remaining,state,"
                 "IFNULL(last_copy_utc,''),updated_at FROM airwatcher_status ORDER BY asiair");
}

}  // namespace airwatcher
